--- #YAML:1.0
name:                Memoize-Attrs
version:             0.00_02
abstract:            Add memoization with subroutine attributes
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_04
author:              Adriano R. Ferreira <ferreira@cpan.org>
distribution_type:   module
requires:     
    Attribute::Handlers:           0
    Memoize:                       0
    Test::More:                    0
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
